### ISSUE TITLE
No subscriber messages received

### ISSUE THREAD

**Issue by FuzzyPones** [karpy47/php-mqtt-client#5] opened 2018-08-10 09:24 UTC
Using mosquitto as Broker i do not get any (retained) subscriber messages using the example code.
I can get the message with the mosquitto CLI subscriber.

**Comment by karpy47** [comment] 2018-08-11 05:36
Have not tested on Mosquitto, rather Apache ActiveMQ where the code works fine for me.
There is a simple debug feature that might help, try something like this to get console output: `$client->setDebug(true);`.

**Comment by karpy47** [comment] 2018-11-22 20:18
Please confirm that it is solved

**Comment by tobbexiv** [comment] 2018-11-24 17:38
I also use mosquitto and can confirm that I can receive retained messages and normal messages. But, I have the issue that not all subscriber messages are received. This is caused by me trying to establish a permanent subscribe (infinite loop retrieving messages all the time) and you closing the stream in case an EOF is received (which seems to happen every time after mosquitto has no further messages to deliver). Now the time between the closing of the stream and me re-opening the connection is not covered and messages sent during this timeframe will not be received by me.

So, what happens:
* I open the connection.
* A retained message is received,
* The connection is closed.
* I reopen the connection.
* ...

If I try to circumvent this by setting QoS to 1 for the messages, I will get them with every new connect again (there is a read timeout in between). So, the PUBACK is not sent / received by the server. I will try to investigate further, but if you cannot reproduce this with ActiveMQ, then there seems to be an issue with Mosquitto.

**Comment by tobbexiv** [comment] 2018-11-25 18:29
> If I try to circumvent this by setting QoS to 1 for the messages, I will get them with every new connect again (there is a read timeout in between). So, the PUBACK is not sent / received by the server.

I failed here. You do not send the PUBACK by default and I did not set the flag when calling `getPublishMessages`. So, this is no bug, but me not being able to call the method the correct way.

So, to conclude I am able to use your class with mosquitto and also receive subscriber messages there. The only issue I still have is that the connection is closed too often. However, this is a different topic and should be handled in a new issue.

**Comment by karpy47** [comment] 2019-01-12 07:28
Regarding the connection being closed, at least ActiveMQ server has a connection TTL that seems to be 60 seconds by default. It is possible to set up sending of ping messages to keep the connection alive, but if messages are sent that rarely there might not be much point keeping the connection open all the time.

**Comment by karpy47** [comment] 2019-01-12 07:34
Regarding missing PUBACK for QoS 1 messages it has worked well with ActiveMQ. 
Note that the function call requires you to set the boolean sendPubAck to be true, it is false by default.

    public function getPublishMessages($maxMessages = 100, $sendPubAck = false)

**Comment by FuzzyPones** [comment] 2019-02-19 16:19
Just so noone waits for me, I never got it to work and ended up using the bash CLI from mosquitto.

**Closed as completed** 2019-03-10 05:21 UTC
